; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env]
platform = espressif32@6.12.0
framework = espidf
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-Wall
	-Wextra
	-DCONFIG_EPD_DISPLAY_TYPE_ED097OC4
	-DCONFIG_EPD_BOARD_REVISION_LILYGO_T5_47
	; -Wpedantic


[env:T5-ePaper-S3]
extends = env
board = T5-ePaper-S3
build_type = debug
board_build.flash_size = 16MB
board_build.partitions = partitions_singleapp_large.csv
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47_S3
monitor_dtr = 0
monitor_rts = 0
board_build.esp_idf.sdkconfig_defaults = sdkconfig.defaults_T5-ePaper-S3